name: Jira

on:
  pull_request:
    branches: [main]
    paths-ignore: ["*.md"]

# We are using OpenID Connect to authenticate with Azure with secret.
# https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read


jobs:
  call-workflow-jira:
    uses: workleap/wl-reusable-workflows/.github/workflows/reusable-jira-workflow.yml@main
    permissions:
      contents: read
      pull-requests: write
      id-token: write