name: Semgrep scan

on:
  pull_request:
    branches: ["main"]
  workflow_dispatch: {}
  schedule:
    - cron: "8 2 * * 6"

# We are using OpenID Connect to authenticate with Azure with secret.
# https://docs.github.com/en/actions/security-for-github-actions/security-hardening-your-deployments/configuring-openid-connect-in-azure
permissions:
  id-token: write
  contents: read

jobs:
  call-workflow-semgrep:
    permissions:
      actions: read
      contents: read
      security-events: write
    uses: workleap/wl-reusable-workflows/.github/workflows/reusable-semgrep-workflow.yml@main